teste:
	@echo "Teste bem sucedido!"

all: run

install:
	pip3 install -r requirements.txt

run:
	streamlit run src/main.py

git:
	git config --global user.email "joaocvgalescky@gmail.com"
	git config --global user.name "Joaogalescky"