test:
	@echo "Test Well Succeded"

all: run

install:
	pip3 install -r requirements.txt
	
run:
	python src/criptografiaAssimetrica.py

git:
	git config --global user.email "joaocvgalescky@gmail.com"
	git config --global user.name  "Joaogalescky"