aula:
	@echo "Aula de Segurança e Auditoria"

all: run

install:
	pip3 install -r requirements.txt
	
run:
	python src/criptografiaSimetrica.py

git:
	git config --global user.email "joaocvgalescky@gmail.com"
	git config --global user.name  "Joaogalescky"